// <auto-generated />
using System;
using BrahmsLab.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrahmsLab.DataAccess.Migrations
{
    [DbContext(typeof(BrahmsLabDbContext))]
    [Migration("20250721054136_AddSpectrumDataToScan")]
    partial class AddSpectrumDataToScan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BrahmsLab.Core.Models.SpectralScan", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CloudId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExsicataIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeciesName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpectrumJsonData")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.ToTable("SpectralScans");
                });
#pragma warning restore 612, 618
        }
    }
}
